site/files/Models/BaseEntity.cs
namespace VWAT.Models
{
  public abstract class BaseEntity
  {
    public long Id { get; set; }
    public abstract string EntityName { get; }
  }
}

site/files/Models/CommentModel.cs
namespace VWAT.Models
{
  public class CommentModel : BaseEntity
  {
    public string Description { get; set; }

    public System.DateTime Date { get; set; }

    public override string EntityName => "Comment";
  }
}

site/files/Models/ErrorViewModel.cs
namespace VWAT.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

site/files/Models/UserModel.cs
using VWAT.Enums;

namespace VWAT.Models
{
  public class UserModel : BaseEntity
  {
    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public UserRole Role { get; set; }

    public string Document { get; set; }

    public UserModel WithoutPassword() => new UserModel { Id = Id, Name = Name, Email = Email, Role = Role, Document = Document };

    public override string EntityName => "User";
  }
}

site/files/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using VWAT.Models;
using VWAT.Services;

namespace VWAT.Controllers
{
  [Route("api/[controller]")]
  public class CommentController : Controller
  {
    private CommentService _service;
    public CommentController(CommentService service) => _service = service;

    [HttpPost]
    public IActionResult Post([FromBody] CommentModel comment)
    {
      if (!string.IsNullOrEmpty(comment?.Description))
      {
        _service.Add(comment.Description);
        return Ok();
      }
      else
        return UnprocessableEntity("Invalid request");
    }

    [HttpGet]
    public IActionResult Get() => Ok(_service.GetAll());

    [HttpDelete("{id}")]
    public IActionResult Delete(int id)
    {
      _service.Remove(id);
      return Ok();
    }
  }
}

site/files/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VWAT.Models;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using VWAT.Services;

namespace VWAT.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;
    private readonly UserService _userService;

    public HomeController(ILogger<HomeController> logger, UserService userService)
    {
      _logger = logger;
      _userService = userService;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Privacy() => View();

    [HttpGet]
    public IActionResult Login() => View();

    [HttpPost]
    public IActionResult Login(string name, string password)
    {
      var login = _userService.Login(name, password);

      if (login is null)
      {
        return View("Index");
      }

      var claims = new List<Claim>() { new Claim(ClaimTypes.Role, "Administrator"), new Claim(ClaimTypes.Name, login.Email) };
      var identity = new ClaimsIdentity(claims, "User Identity");
      var userPrincipal = new ClaimsPrincipal(new[] { identity });

      HttpContext.SignInAsync(userPrincipal);
      return RedirectToAction("Index", "Home");

      // return SignIn(userPrincipal, new AuthenticationProperties(), CookieAuthenticationDefaults.AuthenticationScheme);
      // return View("Index");
    }

    public IActionResult Logout()
    {
      var name = User.Identity.Name;
      HttpContext.SignOutAsync();
      return RedirectToAction("Index", "Home");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

// https://developer.okta.com/blog/2019/11/15/aspnet-core-3-mvc-secure-authentication

site/files/Controllers/TokenController.cs
using Microsoft.AspNetCore.Mvc;
using VWAT.Models;
using VWAT.Services;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.IdentityModel.Tokens;
using VWAT.Config;

namespace VWAT.Controllers
{
  [Route("api/[controller]")]
  public class TokenController : Controller
  {
    private UserService userService;
    private AppConfig appConfig;

    public TokenController(UserService userService, AppConfig appConfig)
    {
      this.userService = userService;
      this.appConfig = appConfig;
    }

    [HttpPost]
    public IActionResult Post([FromBody] UserModel user)
    {
      UserModel login = null;
      if (!string.IsNullOrEmpty(user.Name) && !string.IsNullOrEmpty(user.Password))
        login = userService.Login(user.Name, user.Password);
      if (login is null)
        return Unauthorized();

      var tokenHandler = new JwtSecurityTokenHandler();

      var key = Encoding.ASCII.GetBytes(appConfig.JwtKey);
      var tokenDescriptor = new SecurityTokenDescriptor
      {
        Subject = new ClaimsIdentity(new Claim[]
          {
            new Claim(ClaimTypes.Name, user.Id.ToString())
          }),
        Expires = System.DateTime.UtcNow.AddDays(7),
        SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
      };

      var token = tokenHandler.WriteToken(tokenHandler.CreateToken(tokenDescriptor));
      return Ok(new { Token = token, User = login });
    }
  }
}

site/files/Controllers/XssController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using VWAT.Services;

namespace VWAT.Controllers
{
  public class XssController : Controller
  {
    private CommentService _service;

    public XssController(CommentService service)
    {
      _service = service;
    }

    [HttpGet]
    public IActionResult XssReflected()
    {
      var list = _service.GetAll();
      return View(list);
    }

    [HttpPost]
    public IActionResult FilterComments(string search)
    {
      ViewBag.Filter = search;
      var list = _service.GetAll();
      if (!string.IsNullOrEmpty(search))
        list = list.Where(p => p.Description.Contains(search));
      return View("XssReflected", list);
    }

    [HttpGet]
    public IActionResult XssStorage()
    {
      ViewBag.Comments = _service.GetAll();
      return View();
    }

    [HttpPost]
    public IActionResult SaveStorage(string comment)
    {
      _service.Add(comment);
      ViewBag.Comments = _service.GetAll();
      return View("XssStorage");
    }

    public IActionResult Delete(int id)
    {
      if (id == 0)
        return NotFound();

      _service.Remove(id);
      ViewBag.Comments = _service.GetAll();
      return View("XssStorage");
    }
  }
}

site/files/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

site/files/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WAVT</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="toolbar">
        <span class="app-title">Vulnerable Web Application for Testing</span>
        @if (User.Identity.IsAuthenticated)
        {
            <span class="logged-name">@User.Identity.Name</span>
            <a class="btn" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
        }
        else
        {
            <form asp-action="Login" class="login-form">
                <input class="form-input" name="name" placeholder="Name">
                <input class="form-input" type="password" name="password" placeholder="Password">
                <button class="btn">Login</button>
            </form>
        }
    </header>
    <div class="root-container">
        <section class="sidebar">
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Brute Force</a>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Command Injection</a>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">CSRF</a>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">File Inclusion</a>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">File Upload</a>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Home</a>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Session Hijaking</a>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Sql Injection</a>
            <a asp-area="" asp-controller="Xss" asp-action="XssReflected">XSS (Reflected)</a>
            <a asp-area="" asp-controller="Xss" asp-action="XssStorage">XSS (Stored)</a>
            <div class="footer">
                &copy; 2020 - VWAT
            </div>
        </section>
        <main role="main" class="base-container">
            @RenderBody()
        </main>
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

site/files/Views/Xss/XssReflected.cshtml
@model System.Collections.Generic.IEnumerable<VWAT.Models.CommentModel>

<h2 class="page-title">Cross-site Scripting (Reflected)</h2>
<form asp-controller="Xss" asp-action="FilterComments">
    <input class="form-input" name="search" />
    <button class="btn">search</button>
    <br />
    <br />
    <h4>Results for "@Html.Raw(@ViewBag.Filter)"</h4>
    <br />
</form>
@if(Model.Any())
{
    <div class="comment-box">
    @foreach (var c in Model)
    {
        <div class="comment-line">
        <span>@c.Id - @c.Description</span>
        </div>
    }
    </div>
}

site/files/Views/Xss/XssStorage.cshtml
<h2 class="page-title">Cross-site Scripting (Storage)</h2>
<form asp-action="SaveStorage" style="margin-top:20px">
  <input name="comment" />
  <button class="btn">save comment</button>
  <br />
  <br />
</form>
<div class="comment-box">
  @foreach (var comment in ViewBag.Comments)
  {
    <div class="comment-line">
      <span>@Html.Raw($"{comment.Id} - {comment.Description}")</span>
      <a asp-action="Delete" asp-route-id="@comment.Id" class="btn warn">REMOVE</a>
    </div>
  }
</div>